apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: elasticsearch-logging
  namespace: efklog
  labels:
    k8s-app: elasticsearch-logging
    version: v7.3.2
spec:
  serviceName: elasticsearch-logging
  replicas: 2
  selector:
    matchLabels:
      k8s-app: elasticsearch-logging
      version: v7.3.2
  template:
    metadata:
      labels:
        k8s-app: elasticsearch-logging
        version: v7.3.2
    spec:
      serviceAccountName: elasticsearch-logging
      containers:
      - name: elasticsearch-logging
        image: docker.elastic.co/elasticsearch/elasticsearch:7.3.2
        imagePullPolicy: IfNotPresent

        env:
        - name: cluster.name
          value: elasticsearch-logging
        - name: node.name
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: discovery.seed_hosts
          value: elasticsearch-logging
        - name: cluster.initial_master_nodes
          value: elasticsearch-logging-0,elasticsearch-logging-1
        - name: ES_JAVA_OPTS
          value: "-Xms1g -Xmx1g"

        resources:
          limits:
            cpu: 1000m
            memory: 2Gi
          requests:
            cpu: 500m
            memory: 1Gi

        ports:
        - containerPort: 9200
          name: http
        - containerPort: 9300
          name: transport

        volumeMounts:
        - name: elasticsearch-data
          mountPath: /usr/share/elasticsearch/data

      volumes:
      - name: elasticsearch-data
        emptyDir: {}

      initContainers:
      - name: elasticsearch-init
        image: alpine:3.18
        command: ["sysctl", "-w", "vm.max_map_count=262144"]
        securityContext:
          privileged: true
