apiVersion: v1
kind: Service
metadata:
  name: kibana-logging
  namespace: efklog
  labels:
    k8s-app: kibana-logging
spec:
  ports:
  - name: http
    port: 5601
    targetPort: ui
    protocol: TCP
  selector:
    k8s-app: kibana-logging
  type: LoadBalancer
